### ISSUE TITLE
__del__ method missing

### ISSUE THREAD

**Issue by maurobaraldi** [informationsea/Yet-Another-Kyoto-Cabinet-Python-Binding#1]
I read [here](http://pythonhosted.org/yakc/limitation.html) that you found some technical limitations to implement dictionary's "del" method.

What if you assume an aproach using dictionary's pop method, and returning None?

**Comment by informationsea** [comment]
The cause of the limitation of "del" is C binding of python, not kyoto cabinet. [pop method](http://pythonhosted.org/yakc/kyotodb.html#yakc.pop) is implemented and it works like a normal dictionary.
